@extends('components.layout')

@section('content')
  <div class="container md:py-14">
      <h1 class="text-2xl md:text-3xl lg:text-5xl font-bold my-5">Desa Sibang Gede</h1>
      <div class="py-3">
        <div id="map" class="w-full lg:w-1/2 float-right ml-4 mb-4">
            <iframe class="w-full h-[400px]" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d31561.845519748196!2d115.19964480085729!3d-8.573803917654962!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dd23e9c75836f47%3A0x4b5df247888cde3a!2sSibang%20Gede%2C%20Kec.%20Abiansemal%2C%20Kabupaten%20Badung%2C%20Bali!5e0!3m2!1sid!2sid!4v1715745238437!5m2!1sid!2sid"  style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
        <p class="text-justify my-3 text-sm lg:text-[16px] font-open-sans leading-normal">Baladwipa dimasa silam memendam sejarah pemerintahan oleh Raja – raja yang acap kali sebagai kerajaan merdeka yang berdiri sendiri , namun kadang kala hidup berdampingan dengan kerajaan – kerajaan besar di pulau jawa , bahkan tidak jarang pada kurun waktu tertentu merupakan jajahan dari Kerajaan – kerajaan besar di pulau Jawa , namun sebaliknya sering kali raja – raja Bali mampu menguasai daerah Jawa bagian Timur yaitu Blambangan dan Pasuruan , bahkan pulau Lombok dan Sumbawa. Zaman kerajaan di Bali mencapai puncak keemasannya pada masa pemerintahaan Dalem Çri Batur Renggong yang  melepaskan diri dari  kekuasaan Majapahit di Jawa pada pertengahan abad ke XVI, Ketika itu Gelgel menjadi pusat pemerintahan negeri.
        </p>
        <p class="text-justify my-3 text-sm lg:text-[16px] font-open-sans leading-normal">Namun pada masa pemerintahan Dalem Çri Di Made Keraton Gelgel Hancur lebur karena terjadi perebutan kekuasaan pada tahun 1651 Masehi yang dilakukan oleh Kiayi Agung Maruti dalam kedudukannya sebagai Patih Agung , sehingga sejak saat itu Bali terpecah menjadi kerajaan – kerajaan kecil yang masing – masing memiliki kekuasaan Mandiri. Kiayi Agung Maruti memerintahkan kerajaan Gelgel, yang tidak utuh lagi selama 26 tahun, sehingga akhirnnya gelgel bisa direbut kembali oleh putra bungsu Dalem Çri Di Made yang bernama Dewa  Agung Jambe.Tersebutlah Kiayi Agung Maruti beserta keluarga dan Pengikut pengikutnya melarikan diri mengungsi ke hutan Jimbaran di sebelah selatan Badung.
        </p>
        <p class="text-justify my-3 text-sm lg:text-[16px] font-open-sans leading-normal">Selanjutnya babat Mengwi menyebutkan, bahwa beliau pergi kebarat hingga Desa Kapal kemudian kembali lagi ketimur hingga memasuki hutan rangkan, yang dalam perkembangannya kemudian disebut kuramas, dan dijadikan   kekuasaannya  yang  baru, kemudian kerajaan itu dibagi dua yaitu : Putra tertua I Gusti Agung Putu merintah daerah timur dengan kedudukan dikuramas, sedangkan putra bungsu, I Gusti Agung Anom bergelar I Gusti Agung Made Agung, memerintahkan daerah Barat, bertempat di Kapal, Putra bungsu inilah yang menurunkan para bangsawan Manguwi yang ikut menentukan sebagai daerah Sibang kemudian , Putra satu – satunnya dari I Gusti Agung Made Agung oleh karena memohon di Pura Sada kapal yaitu I Gusti Agung Putu membawa daerah kekuasaannya kepuncak kebesarannya dengan melahirkan kerajaan Mangui ( Mangapura ) yang mewilayahi daerah yang luas , berkat wara lugraha Hyang ing Puncak Mangu , di selatan : Jimbaran , Huluwatu dan Barawa, di Timur : Sebeleh barat Sungai Petanu , di Barat : Jembrana hingga dataran Blambangan di ujung Jawa Timur , di Utara daerah  Panji  Sakti  Buleleng.
        </p>
      </div>
      <div class="py-3">
        <img class="float-left w-full lg:w-1/2 mr-4 mb-4" src="{{asset('/main_asset/img/beranda.webp')}}" alt="Pura Dalem Sejati" data-aos="fade-right" data-aos-duration="1000">
        
        <p class="text-justify text-sm lg:text-[16px] font-open-sans leading-normal">Seteleh Abiseka Ratu beliau bergelar Cokorda Sakti Blambangan, diceritakan sekarang tentang daerah Sibang  yang  terletak di sisi timur aliran sungai Ayung sudah sejak sedia kala di huni oleh penduduk terutama ( dibagian selatan ) yaitu Serijati dan Cabe sedangkan di bagian utara hingga daerah mambal masih merupakan hutan belantara. Dinamakan Saibang konon pada Zaman dahulu seputar sisi timur Desa ditanami pohon Pucuk Baang ( Kembang sepatu merah ). Sehingga setiap waktu dari jauh selalu kelihatan merah menyala sehingga daerah itu dijuluki Saibaang ( selalu merah ). Tatkala kerajaan Mengwi , dibawah cokorda sakti Blambangan mengembangkan wilayahnnya sudah tentu Anglurah Sibang Serijati ikut menyatakan takluk kepada beliau bersama – sama dengan Anglurah Pacung. ( Payangan ) , Yeh Tengah, Mambal, Blahbatuh dan lainnya lagi. Untuk mengawasi dan memerintahkan daerah Saibang Serijati diserahkan kepada salah seoarang Putra beliau yang bernama I Gusti Agung Made Kamasan.
        </p>
        <p class="text-justify my-3 text-sm lg:text-[16px] font-open-sans leading-normal">Tiba saatnya Ida Cokorda Sakti Blambangan mangkat dan diganti oleh Putra Beliau yang bernama Ida Cokorda  Agung Made Banya. Pada suatu hari  Ida Cokorda  Agung  Made Banya  melakukan inspeksi ke daerah Blambangan , maka untuk mengawasi Puri beliau di Mangwi pemerintah sementara di serahkan kepada Kakak beliau yaitu  I Gusti Agung Made Kamasan  Saibaang Srijati. Timbul pikiran dari  I Gusti Agung Made Kamasan untuk merebut Singasana kekuasaan adindanya menjadi Raja Mengwi. Maksudnya itu disokong oleh Manggis Kuning Gianyar . namun akhirnya Gagal  karena Cokorda  Agung Made Banya kembali dari Blambangan maka  I Gusti Agung Made Kamasan menyingkir beserta sikep pengiringnya ke utara yaitu di Banjar Sayan , dan selanjutnya bersama – sama para Busana Sayan mengungsi ke daerah Den kayu. 
        </p>
        <p class="text-justify my-3 text-sm lg:text-[16px] font-open-sans leading-normal">Tanpa digubris oleh Adinda Raja  beliau Raja Mengwi , maka perjalanan terus dilanjutkan menuju daerah Tampak Siring. Tidak beberapa lama rombongan beliau tersebut pindah kedaerah kerajaan Badung dan oleh Badung atau Raja Badung diberikan tempat tinggal di Ubung. Cukup lama beliau menetap di sana disungsung oleh para Ampel Gading Akhirnya pada suatu ketika dibuatlah layang – layang yang  besar dan pada ekor layangan itu diikatkan sepucuk surat untuk adinda beliau Raja Mengwi dengan maksud bahwa beliau akan kembali lagi ke daerah Mengwi yaitu daerah Saibang Serijati, hanya beliau minta agar diberikan tambahan daerah lagi yaitu, daerah Sempidi, Lukluk, Perang dan Anggungan. Tambahan pula agar beliau tidak kehilangan, maka diharapkan agar daerah-daerah tersebut seakan-akan jatuh melalui suatu peperangan.
        </p>
      </div>
      <div class="py-3">
        <img class="w-full lg:w-1/2 float-right ml-4 mb-4" src="{{asset('/main_asset/img/beranda1.webp')}}" alt="Pura Dalem Sejati" data-aos="fade-left" data-aos-duration="1000">
        
        <p class="text-justify text-sm lg:text-[16px] font-open-sans leading-normal">Tanpa digubris oleh Adinda Raja  beliau Raja Mengwi , maka perjalanan terus dilanjutkan menuju daerah Tampak Siring. Tidak beberapa lama rombongan beliau tersebut pindah kedaerah kerajaan Badung dan oleh Badung atau Raja Badung diberikan tempat tinggal di Ubung. Cukup lama beliau menetap di sana disungsung oleh para Ampel Gading Akhirnya pada suatu ketika dibuatlah layang – layang yang  besar dan pada ekor layangan itu diikatkan sepucuk surat untuk adinda beliau Raja Mengwi dengan maksud bahwa beliau akan kembali lagi ke daerah Mengwi yaitu daerah Saibang Serijati, hanya beliau minta agar diberikan tambahan daerah lagi yaitu, daerah Sempidi, Lukluk, Perang dan Anggungan. Tambahan pula agar beliau tidak kehilangan, maka diharapkan agar daerah-daerah tersebut seakan-akan jatuh melalui suatu peperangan.
        </p>
        <p class="text-justify my-3 text-sm lg:text-[16px] font-open-sans leading-normal">Penyerangan mula-mula ditujukan ke Cabe, namun induk pasukan karang Buncing mundur dan dipusatkan disisi utara seberang sungai Ayung dengan pertahanan lembah sungai yang tangguh dan kuat secara diam-diam pasukan I Gusti Agung Made Kamasan melakukan gerakan penyusupan ke Utara melalui tanah Ayu, kemudian menyeberang sungai Ayung ke Timur dan menyerang dari Utara maka kalahlah Karang Buncing dan jatuhlah Saibang Serijati.  Dibawah  I Gusti Agung Made Kamasan kembali ke Puri Tegal ditinggalkan dan mulai dibangun Puri di Sibang bersama-sama rakyat terutama para Busana Sayan, disinilah beliau menetap dan beranak pinak masih dalam kaitan dengan kerajaan Mengwi. Karena Perputaran jaman Mengwi mulai mundur suatu ketika daerahnya Anglurah Mambal diserang oleh Cokorde Tapisan keturunan Sukawati sehingga kalah dan minta perlindungan kepada IGA. Ketut  Kamasan  diberikan bertempat tinggal di Sibang bagian Utara dinamakan Sibangkaja.
        </p>
        <p class="text-justify my-3 text-sm lg:text-[16px] font-open-sans leading-normal">Demikian pula Anglurah Bun berani menyatakan diri merdeka lepas dari kekuasaan Mengwi, maka terjadilah perang antara pasukan Bun diserang dari Utara oleh pasukan Mengwi dibawah IGA. Made Munggu dan dari barat oleh pasukan Saibang dibawah pimpinan  IGA. Ketut Kamasan, Anglurah Bun kalah sanak keluarga yang menyerah ke Sibang diberi tempat tinggal di Banjar Bantas, sedang Begawantanya dibuatkan Geriya didekat Pura Dalem Setra Sibang dinamakan Geriya Dalem, namun kemunduran kerajaan Mengwi tidak terbendung lagi, baik karena gangguan dari luar maupun karena factor pengendali kerajaan itu sendiri sudah tentu keadaan daerah Saibang pun seirama dengan kerajaan Mangapura.
        </p>
        <p class="text-justify my-3 text-sm lg:text-[16px] font-open-sans leading-normal">Sejarah selanjutnya menyebutkan bahwa kerajaan Mengwi dikalahkan oleh kerajaan Badung. Tiada berapa lama kemudian kerajaan Badung dan Kelungkung dalam perang Puputan masing-masing tahun 1908 dikalahkan oleh Kompeni Belanda. Berdasarkan tata pemerintahan Kompeni maka daerah Sibang pernah menjadi satu Punggawa Abiansemal. Pada jaman kemerdekaan dengan pemerintah RI yang berdaulat Sibang terbagi menjadi dua desa :  Desa Sibangkaja dan Desa Sibanggede. Demikian sekedar asal usul dari lahirnya nama dan tempat Desa Sibanggede.
        </p>
      </div>
  </div>


@endsection